# Generated by Django 5.2.7 on 2025-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.IntegerField(help_text='in minutes')),
                ('difficulty', models.CharField(editable=False, max_length=50)),
            ],
        ),
    ]
